### ISSUE TITLE
Team Meeting - 2024-10-02 16:30 - 17:30

### ISSUE THREAD

**Issue by rafeymalik1** [russellrd/realm#30]
**Date and Time**
2024-10-02 16:30 - 17:30

**Attendance**

- [ ] Rafey
- [ ] Russell
- [ ] Avanish
- [ ] Abdul

**Agenda**

- Review completed work
- Discuss any uncertainties
- Discuss and split up remaining work + adding work to latex file.

**Comment by 1Midnight1** [comment]
duplicate
