### ISSUE TITLE
TA Meeting - 2024-10-21 15:45-16:00

### ISSUE THREAD

**Issue by 1Midnight1** [russellrd/realm#63]
**Purpose of Meeting**

**Date and Time**
October 21, 2024
03:45pm-04:00pm

**Attendance**

- [ ] Rafey
- [x] Russell
- [ ] Avanish
- [x] Abdul

**Questions to Ask**

- How exactly should the FMEA table be structured? 
- For the FMEA table, how do we incorporate general failure modes like the device running out of power or access to sensor data being denied by the device's system? Do we mention these cases under every Design Function?
- Do we need to consider possible errors that are already covered by our functional requirements?

**Comment by 1Midnight1** [comment]
- FMEA table structure is fine, similar to example
- Start with major failure modes, consider other cases as they become relevant
- We should consider real world hazards resulting from the use of our app

**Comment by russellrd** [comment]
FMEA
- Components can span multiple hazards
- What hazards?
  - Not too deep but the major concerns
  - Don’t have to redo things covered by SRS
  - Security
  - Cultural (eg facebook)
    - Waivers for tours
  - Physical
    - User runs into a wall
