### ISSUE TITLE
Team Meeting - 2024-11-18 - 2:30pm - 4:30 pm

### ISSUE THREAD

**Issue by rafeymalik1** [russellrd/realm#99]
**Attendance**

- [x] Rafey
- [x] Russell
- [x] Avanish
- [x] Abdul

**Agenda**

- Talk about module guide
- Talk about splitting up the various parts of the project
- Talk about how to implement the database

**Comment by 1Midnight1** [comment]
Data storage requirements:
- Object database (stores AR object attributes)
- Object instance database (objects mapped to locations irl)
- User Profile database (stores user profile data)
- User Sub-realms (maps users to sub-realms)
- User Friends (maps users to users)
- Storage for model data, profile pictures, etc. (do we want binaries in database or references to files?)

**Comment by 1Midnight1** [comment]
Action Items:
- [ ] Write 5 likely and unlikely changes per person in module guide
